location              = "eastus"
resource_group_name   = "buyersmarket"
storage_account_name  = "buyersmarketstore"
app_service_plan_name = "buyersmarketasp"
app_insights_name     = "buyersmarket"
function_name         = "buyersmarket"